# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElixionBridge < Formula
  desc "Connect your AI agents to Elixion.io"
  homepage "https://elixion.io"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.0/elixion-bridge_1.0.0_darwin_amd64.tar.gz"
      sha256 "a1dab99e3a1cc1e5dba160254904ea2dca45711f62d4d91a3b789f28e88c9b7c"

      def install
        bin.install "elixion-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.0/elixion-bridge_1.0.0_darwin_arm64.tar.gz"
      sha256 "52c7826718b51bc4b6ef7cc877b23b1940541c6e0dc2f93e3ff3709c1a1f1ebc"

      def install
        bin.install "elixion-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.0/elixion-bridge_1.0.0_linux_amd64.tar.gz"
      sha256 "5c7cd169a7ea848a6c3e7de6d876c8c54d9cff60ce5b62479225c11e0584e7f9"
      def install
        bin.install "elixion-bridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.0/elixion-bridge_1.0.0_linux_arm64.tar.gz"
      sha256 "e0971ae3594a390227fd4004019602965eb20e5bc5b8f6b340dba60df61ca4d0"
      def install
        bin.install "elixion-bridge"
      end
    end
  end

  test do
    system "#{bin}/elixion-bridge", "version"
  end
end
