# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ElixionBridge < Formula
  desc "Connect your AI agents to Elixion.io"
  homepage "https://elixion.io"
  version "1.0.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.2/elixion-bridge_1.0.2_darwin_amd64.tar.gz"
      sha256 "6e08d04b40ea7b25e7919adf2dd75906481fab5df62af87d5e3080cf531c3d0f"

      def install
        bin.install "elixion-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.2/elixion-bridge_1.0.2_darwin_arm64.tar.gz"
      sha256 "a9f8f148d45305f65468dd7cfebd76c93f3ea2a00ca9df688f4b6db4b91a9530"

      def install
        bin.install "elixion-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.2/elixion-bridge_1.0.2_linux_amd64.tar.gz"
      sha256 "b1b37e841a0b685b8e21c49a6a37edff88c2688bfa21b05d1c7075f13e25d111"
      def install
        bin.install "elixion-bridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Elixion-ai/homebrew-tap/releases/download/v1.0.2/elixion-bridge_1.0.2_linux_arm64.tar.gz"
      sha256 "c5d82938e14d94d37cab9df53e3e1813baa13c165f83a9a654015702a73da923"
      def install
        bin.install "elixion-bridge"
      end
    end
  end

  test do
    system "#{bin}/elixion-bridge", "version"
  end
end
