# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class ElixionBridge < Formula
  desc "Connect your AI agents to Elixion.io"
  homepage "https://elixion.io"
  version "1.0.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Elixion-ai/elixion.io/releases/download/v1.0.0/elixion-bridge_1.0.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "152c02307c371e290102fc0c5aea477b370356c47441a571f28b5f9512688d4e"

      def install
        bin.install "elixion-bridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Elixion-ai/elixion.io/releases/download/v1.0.0/elixion-bridge_1.0.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fa95b57a3829fb5520c4dc91121bad589ca11cff474e66ba16728557ed2dcf30"

      def install
        bin.install "elixion-bridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Elixion-ai/elixion.io/releases/download/v1.0.0/elixion-bridge_1.0.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e1b117aca22d6d1d8a0c26dd3ca861c83d0f3bc948f70e3f9b2bd093bb0a2b71"
      def install
        bin.install "elixion-bridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Elixion-ai/elixion.io/releases/download/v1.0.0/elixion-bridge_1.0.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "371caf3fa745a302a949d69e133211fd8dd2dc6f2482d1d6f57638faa09d98a1"
      def install
        bin.install "elixion-bridge"
      end
    end
  end

  test do
    system "#{bin}/elixion-bridge", "version"
  end
end
